# Generated by Django 5.0.4 on 2024-04-22 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_number', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('branch_code', models.CharField(max_length=230)),
                ('currency', models.CharField(max_length=230)),
                ('pin', models.CharField(max_length=4)),
                ('balance', models.DecimalField(decimal_places=50, max_digits=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('cell', models.CharField(max_length=25)),
                ('national_id', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_news', models.BooleanField(default=True)),
                ('receive_promotions', models.BooleanField(default=True)),
                ('receive_alerts', models.BooleanField(default=True)),
                ('receive_transaction_message', models.BooleanField(default=True)),
                ('receive_pin_change_alert', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=230)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='core.account')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='core.account')),
            ],
        ),
    ]
