# Generated by Django 5.0.4 on 2024-04-22 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_account_personal_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='personal_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.personalinfo'),
        ),
    ]
