# Generated by Django 5.0.4 on 2024-04-22 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_preferences_account_account_preferences_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='preferences',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.preferences'),
        ),
    ]
